export const ANGEBOT_TEXT = "Angebot"
export const HOME_TEXT = "Home"
export const LATAKIA_GMBH = "Latakia GmbH"
export const NEXT_TEXT = "Next"
export const BACK_TEXT = "Back"
export const SERVICES_TITLE_TEXT = "Unsere Dienstleistungen"